# Generated by Django 3.2.25 on 2024-09-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20240511_1931'),
        ('chatgpt', '0004_create_lesson_information_default_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, help_text='본문', null=True)),
                ('status', models.CharField(choices=[('PROCESSING', '처리중'), ('DONE', '처리완료'), ('FAIL', '실패')], default='PROCESSING', help_text='처리상태', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_summary', to='board.post')),
            ],
            options={
                'verbose_name': '게시글 요약',
                'verbose_name_plural': '게시글 요약',
            },
        ),
    ]
