# Generated by Django 3.2.25 on 2024-06-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePopupModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='popup/')),
                ('description', models.TextField(blank=True, null=True, verbose_name='관리자 보기 위한 설명')),
                ('on_click_link', models.TextField(null=True, verbose_name='이미지 클릭 시 링크')),
                ('height', models.PositiveIntegerField(verbose_name='모달 높이')),
                ('width', models.PositiveIntegerField(verbose_name='모달 너비')),
                ('sequence', models.PositiveIntegerField(db_index=True, default=1, help_text='숫자가 작을수록 앞에 있음', verbose_name='앞에 있는 순서')),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='종료 시간')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '홈 팝업 모달',
                'verbose_name_plural': '홈 팝업 모달',
            },
        ),
    ]
