# Generated by Django 3.2.25 on 2024-06-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepopupmodal',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='homepopupmodal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='homepopupmodal',
            name='on_click_link',
            field=models.TextField(blank=True, null=True, verbose_name='이미지 클릭 시 링크'),
        ),
    ]
