# Generated by Django 3.2.25 on 2024-05-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20220406_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_count',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rereply_count',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
